POST http://localhost:3000/api/v1/user
Content-Type: application/json

{
  "firstname":"newUserFirst",
  "lastname": "newUserLast",
  "email": "test@email.com",
  "password": "1234",
  "roleid": 1
}

###
POST http://localhost:3000/api/v1/user/login
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "1234"
}


