POST localhost:3000/api/v1/user
Content-Type: application/json

{
  "firstname": "newUserFirst",
  "lastname": "newUserLast",
  "email": "test@email.com",
  "password": "1234",
  "roleid": 1
}
###
GET localhost:3000/api/v1/tickets/price/:originId&:destinationId


###
POST localhost:3000/api/v1/user/login
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "1234"
}

###
PUT localhost:3000/users

###
POST localhost:3000/api/v1/tickets/purchase/subscription
Content-Type: application/json

{
  "origin": "1",
  "destination": "2",
  "tripdate": "2023-12-22"
}

###
POST localhost:3000/api/v1/user/login
Content-Type: application/json

{
  "email": "senior",
  "password": "1234"
}

###
POST localhost:3000/api/v1/user/login
Content-Type: application/json

{
  "email": "weaee",
  "password": "1"
}

###
PUT localhost:3000/api/v1/requests/senior/1

###
GET localhost:3000/api/v1/tickets/price/4/1


###
POST localhost:3000/api/v1/senior/request
Content-Type: application/json

{
  "nationalid": "312"
}